config/routes.rb
Rails.application.routes.draw do
  resources :logo_texts
  resources :menu_items
  resources :testimonials
  resources :courses
  resources :corporate_trainer_headings
  resources :corporate_trainers
  resources :pm_logos
  resources :pm_texts
  resources :banner_sections
  resources :positions do
    resources :requirement_categories
  end
  resources :carrer_pages
  resources :policy_hedings do
    resources :policy_sub_hedings
  end
  resources :term_pages
  resources :contact_pages
  resources :teams
  root 'home#index'
  get '/about', to: 'home#about_us', as: 'about'
  get '/contact', to: 'home#contact_us', as: 'contact'
  get '/privacy_policy', to: 'home#privicy_policy', as: 'privacy_policy'  
  get '/terms', to: 'home#t_c', as: 'terms' 
  get 'home/custom'
  post 'home/custom'
  get '/careers', to: 'home#career', as: 'careers'
  get '/admin', to: 'dash#index', as: 'admin'

  devise_for :users, :controllers => { :registrations => "registrations" } 
  resources :about_pages
  
  #routes
end

app/models/policy_heding.rb
class PolicyHeding < ActiveRecord::Base
  has_many :policy_sub_hedings
	has_many :policy_sub_hedings
end

app/controllers/policy_hedings_controller.rb
class PolicyHedingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_policy_heding, only: [:show, :edit, :update, :destroy]

  # GET /policy_hedings
  # GET /policy_hedings.json
  def index
    @policy_hedings = PolicyHeding.all
  end

  # GET /policy_hedings/1
  # GET /policy_hedings/1.json
  def show
  end

  # GET /policy_hedings/new
  def new
    @policy_heding = PolicyHeding.new
  end

  # GET /policy_hedings/1/edit
  def edit
  end

  # POST /policy_hedings
  # POST /policy_hedings.json
  def create
    @policy_heding = PolicyHeding.new(policy_heding_params)

    respond_to do |format|
      if @policy_heding.save
        format.html { redirect_to @policy_heding, notice: 'Policy heding was successfully created.' }
        format.json { render :show, status: :created, location: @policy_heding }
      else
        format.html { render :new }
        format.json { render json: @policy_heding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policy_hedings/1
  # PATCH/PUT /policy_hedings/1.json
  def update
    respond_to do |format|
      if @policy_heding.update(policy_heding_params)
        format.html { redirect_to @policy_heding, notice: 'Policy heding was successfully updated.' }
        format.json { render :show, status: :ok, location: @policy_heding }
      else
        format.html { render :edit }
        format.json { render json: @policy_heding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policy_hedings/1
  # DELETE /policy_hedings/1.json
  def destroy
    @policy_heding.destroy
    respond_to do |format|
      format.html { redirect_to policy_hedings_url, notice: 'Policy heding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy_heding
      @policy_heding = PolicyHeding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_heding_params
      params.require(:policy_heding).permit(:heading, :position)
    end
end

app/helpers/policy_hedings_helper.rb
module PolicyHedingsHelper
end

app/views/policy_hedings/_form.html.erb
<%= form_for(@policy_heding) do |f| %>
  <% if @policy_heding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@policy_heding.errors.count, "error") %> prohibited this policy_heding from being saved:</h2>

      <ul>
      <% @policy_heding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h2>Heading of privicy Policy</h2>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :heading %><br>
    <%= f.text_field :heading %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/policy_hedings/edit.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<h1>Editing Policy Heding</h1>

<%= render 'form' %>

<%= link_to 'Show', @policy_heding %> |
<%= link_to 'Back', policy_hedings_path %>
</div>

app/views/policy_hedings/index.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;"><p id="notice"><%= notice %></p>

<h1>Listing Policy Hedings</h1>

<table>
  <thead>
    <tr>
      <th>Heading</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @policy_hedings.each do |policy_heding| %>
      <tr>
        <td><%= policy_heding.heading %></td>
        <td><%= link_to 'Show', policy_heding %></td>
        <td><%= link_to 'Edit', edit_policy_heding_path(policy_heding) %></td>
        <td><%= link_to 'Destroy', policy_heding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Policy heding', new_policy_heding_path %>
</div>

app/views/policy_hedings/new.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<h1>New Policy Heding</h1>

<%= render 'form' %>

<%= link_to 'Back', policy_hedings_path %>
</div>

app/views/policy_hedings/show.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3><%=@policy_heding.heading %></h3>
				<%= link_to 'Edit', edit_policy_heding_path(@policy_heding) %> |
				<%= link_to 'Back', policy_hedings_path %>
			</div>
			<div class="panel-body">
				
				<br>
					<h4>All Sub Headings</h4>
			</div>
				 <!-- List group -->
  					<ul class="list-group">		
						<%=render @policy_heding.policy_sub_hedings%>
					</ul>	
					<br>
					
					<div style="margin-left:10px;">
					<h4>Form for new Sub Heading</h4>
					<%= form_for([@policy_heding,@policy_heding.policy_sub_hedings.build]) do |f| %>
  						<h2>Sub Headings </h2>
						  <div class="field">
						    <%= f.label :sub_heading %><br>
						    <%= f.text_field :sub_heading %>
						  </div>

						  <div class="actions">
						    <%= f.submit %>
						  </div>
						<% end %>
					</div>
				<br>
			
		</div>
	</div>
	<div class="col-md-2"></div>
</div>

<br>

</div>