config/routes.rb
Rails.application.routes.draw do
  resources :logo_texts
  resources :menu_items
  resources :testimonials
  resources :courses
  resources :corporate_trainer_headings
  resources :corporate_trainers
  resources :pm_logos
  resources :pm_texts
  resources :banner_sections
  resources :positions do
    resources :requirement_categories
  end
  resources :carrer_pages
  resources :policy_hedings do
    resources :policy_sub_hedings
  end
  resources :term_pages
  resources :contact_pages
  resources :teams
  root 'home#index'
  get '/about', to: 'home#about_us', as: 'about'
  get '/contact', to: 'home#contact_us', as: 'contact'
  get '/privacy_policy', to: 'home#privicy_policy', as: 'privacy_policy'  
  get '/terms', to: 'home#t_c', as: 'terms' 
  get 'home/custom'
  post 'home/custom'
  get '/careers', to: 'home#career', as: 'careers'
  get '/admin', to: 'dash#index', as: 'admin'

  devise_for :users, :controllers => { :registrations => "registrations" } 
  resources :about_pages
  
  #routes
end

app/models/banner_section.rb
class BannerSection < ActiveRecord::Base

	has_attached_file :banner_img,  styles: { medium: "1600x800>", thumb: "100x100>" }, default_url: ":style/missing.jpg"
  	validates_attachment_content_type :banner_img, content_type: /\Aimage\/.*\Z/
  	validates_attachment :banner_img,size: {less_than: 5.megabytes}

  	validates :banner_heading, presence: true, length: { in: 2..91 }
  	validates :banner_button_text, presence: true, length: {in: 2..20}
  	validates :banner_button2_text, presence: true, length: {in: 2..20}
  	validates :banner_button_url, presence: true
  	validates :banner_button2_url, presence: true

end

app/controllers/banner_sections_controller.rb
class BannerSectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_banner_section, only: [:show, :edit, :update, :destroy]

  # GET /banner_sections
  # GET /banner_sections.json
  def index
    @banner_sections = BannerSection.all
  end

  # GET /banner_sections/1
  # GET /banner_sections/1.json
  def show
  end

  # GET /banner_sections/new
  def new
    @banner_section = BannerSection.new
  end

  # GET /banner_sections/1/edit
  def edit
  end

  # POST /banner_sections
  # POST /banner_sections.json
  def create
    @banner_section = BannerSection.new(banner_section_params)

    respond_to do |format|
      if @banner_section.save
        format.html { redirect_to @banner_section, notice: 'Banner section was successfully created.' }
        format.json { render :show, status: :created, location: @banner_section }
      else
        format.html { render :new }
        format.json { render json: @banner_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banner_sections/1
  # PATCH/PUT /banner_sections/1.json
  def update
    respond_to do |format|
      if @banner_section.update(banner_section_params)
        format.html { redirect_to @banner_section, notice: 'Banner section was successfully updated.' }
        format.json { render :show, status: :ok, location: @banner_section }
      else
        format.html { render :edit }
        format.json { render json: @banner_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banner_sections/1
  # DELETE /banner_sections/1.json
  def destroy
    @banner_section.destroy
    respond_to do |format|
      format.html { redirect_to banner_sections_url, notice: 'Banner section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner_section
      @banner_section = BannerSection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_section_params
      params.require(:banner_section).permit(:banner_img, :banner_heading, :banner_button_text, :banner_button_url, :banner_button2_text, :banner_button2_url)
    end
end

app/helpers/banner_sections_helper.rb
module BannerSectionsHelper
end

app/views/banner_sections/_form.html.erb
<%= form_for(@banner_section) do |f| %>
  <% if @banner_section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner_section.errors.count, "error") %> prohibited this banner_section from being saved:</h2>

      <ul>
      <% @banner_section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :banner_img %><br>
    <%= f.file_field :banner_img %>
  </div>
  <div class="field">
    <%= f.label :banner_heading %><br>
    <%= f.text_field :banner_heading %>
  </div>
  <div class="field">
    <%= f.label :banner_button_text %><br>
    <%= f.text_field :banner_button_text %>
  </div>
  <div class="field">
    <%= f.label :banner_button_url %><br>
    <%= f.text_field :banner_button_url %>
  </div>
  <div class="field">
    <%= f.label :banner_button2_text %><br>
    <%= f.text_field :banner_button2_text %>
  </div>
  <div class="field">
    <%= f.label :banner_button2_url %><br>
    <%= f.text_field :banner_button2_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banner_sections/edit.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<h1>Editing Banner Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @banner_section %> |
<%= link_to 'Back', banner_sections_path %>
</div>

app/views/banner_sections/index.html.erb
<div class="asa" style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<p id="notice"><%= notice %></p>

<h1>Listing Banner Sections</h1>
<% @banner_sections.each do |banner_section| %>
<div class="row">
  <div class="col-md-1"></div>  
  <div class="col-md-10">
    <div class="well" >
      <div style="background-image:url(<%=banner_section.banner_img(:medium)%>);height:400px;padding:10px;">
      <h3 style="color:#fff;position:absolute;top:35%;"><%= banner_section.banner_heading %></h3>
      <div style="text-align:center;">
        <a href="<%= banner_section.banner_button_url %>"><div class="btn btn-success btn-lg" style="display:inline-block;position:absolute;top:55%;margin: 0 auto;left:40%;"><%= banner_section.banner_button_text %></div></a>
      </div>
      </div>
      <div style="position:absolute;bottom:0;right:0;background-color:#fff;box-shadow:2px 2px 5px grey;line-height:3em;padding:5px;">
        <%= link_to 'Show', banner_section %> | <%= link_to 'Edit', edit_banner_section_path(banner_section) %> | <%= link_to 'Destroy', banner_section, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </div>
  
</div>
<% end %>
  
  <div class="well" style="width:165px !important;">
    <%= link_to 'New Banner section', new_banner_section_path %>
  </div>
</div>

app/views/banner_sections/new.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<h1>New Banner Section</h1>

<%= render 'form' %>

<%= link_to 'Back', banner_sections_path %>
</div>

app/views/banner_sections/show.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<p id="notice"><%= notice %></p>

<p>
  <strong>Banner img:</strong>
  <%= image_tag @banner_section.banner_img(:medium) %>
</p>

<p>
  <strong>Banner heading:</strong>
  <%= @banner_section.banner_heading %>
</p>

<p>
  <strong>Banner button text:</strong>
  <%= @banner_section.banner_button_text %>
</p>

<p>
  <strong>Banner button url:</strong>
  <%= @banner_section.banner_button_url %>
</p>

<%= link_to 'Edit', edit_banner_section_path(@banner_section) %> |
<%= link_to 'Back', banner_sections_path %>
</div>