config/routes.rb
Rails.application.routes.draw do
  resources :logo_texts
  resources :menu_items
  resources :testimonials
  resources :courses
  resources :corporate_trainer_headings
  resources :corporate_trainers
  resources :pm_logos
  resources :pm_texts
  resources :banner_sections
  resources :positions do
    resources :requirement_categories
  end
  resources :carrer_pages
  resources :policy_hedings do
    resources :policy_sub_hedings
  end
  resources :term_pages
  resources :contact_pages
  resources :teams
  root 'home#index'
  get '/about', to: 'home#about_us', as: 'about'
  get '/contact', to: 'home#contact_us', as: 'contact'
  get '/privacy_policy', to: 'home#privicy_policy', as: 'privacy_policy'  
  get '/terms', to: 'home#t_c', as: 'terms' 
  get 'home/custom'
  post 'home/custom'
  get '/careers', to: 'home#career', as: 'careers'
  get '/admin', to: 'dash#index', as: 'admin'

  devise_for :users, :controllers => { :registrations => "registrations" } 
  resources :about_pages
  
  #routes
end

app/models/about_page.rb
class AboutPage < ActiveRecord::Base

	has_attached_file :img,  styles: { medium: "1351x533>", thumb: "100x100>" }, default_url: ":style/missing.jpg"
  	validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/
  	validates_attachment :img,size: {less_than: 4.megabytes}

  	validates :about, presence: true, uniqueness: true,length: { minimum: 40}
  	validates :vision, presence: true,length: { minimum: 30}
  	validates :mission, presence: true, length: { minimum: 30 }


end

app/controllers/about_pages_controller.rb
class AboutPagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_about_page, only: [:show, :edit, :update, :destroy]

  # GET /about_pages
  # GET /about_pages.json
  def index
    @about_pages = AboutPage.all
  end

  # GET /about_pages/1
  # GET /about_pages/1.json
  def show
  end

  # GET /about_pages/new
  def new
    @about_page = AboutPage.new
  end

  # GET /about_pages/1/edit
  def edit
  end

  # POST /about_pages
  # POST /about_pages.json
  def create
    @about_page = AboutPage.new(about_page_params)

    respond_to do |format|
      if @about_page.save
        format.html { redirect_to @about_page, notice: 'About page was successfully created.' }
        format.json { render :show, status: :created, location: @about_page }
      else
        format.html { render :new }
        format.json { render json: @about_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /about_pages/1
  # PATCH/PUT /about_pages/1.json
  def update
    respond_to do |format|
      if @about_page.update(about_page_params)
        format.html { redirect_to @about_page, notice: 'About page was successfully updated.' }
        format.json { render :show, status: :ok, location: @about_page }
      else
        format.html { render :edit }
        format.json { render json: @about_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /about_pages/1
  # DELETE /about_pages/1.json
  def destroy
    @about_page.destroy
    respond_to do |format|
      format.html { redirect_to about_pages_url, notice: 'About page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about_page
      @about_page = AboutPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_page_params
      params.require(:about_page).permit(:img, :about, :vision, :mission, :extra)
    end
end

app/helpers/about_pages_helper.rb
module AboutPagesHelper
end

app/views/about_pages/_form.html.erb
<%= form_for(@about_page) do |f| %>
  <% if @about_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about_page.errors.count, "error") %> prohibited this about_page from being saved:</h2>

      <ul>
      <% @about_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4>image size should be atlest 1351x533</h4>
    <%= f.label :img %><br>
    <%= f.file_field :img %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_field :about %>
  </div>
  <div class="field">
    <%= f.label :vision %><br>
    <%= f.text_area :vision %>
  </div>
  <div class="field">
    <%= f.label :mission %><br>
    <%= f.text_area :mission %>
  </div>
  <div class="field">
    <%= f.label :extra %><br>
    <%= f.text_area :extra %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/about_pages/edit.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<h1>Editing About Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @about_page %> |
<%= link_to 'Back', about_pages_path %>
</div>

app/views/about_pages/index.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<p id="notice"><%= notice %></p>

<h1>Listing About Pages</h1>

<table>
  <thead>
    <tr>
      <th>Img</th>
      <th>About</th>
      <th>Vision</th>
      <th>Mission</th>
      <th>Extra</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @about_pages.each do |about_page| %>
      <tr>
        <td><%= image_tag about_page.img(:thumb) %></td>
        <td><%= about_page.about %></td>
        <td><%= about_page.vision %></td>
        <td><%= about_page.mission %></td>
        <td><%= about_page.extra %></td>
        <td><%= link_to 'Show', about_page %></td>
        <td><%= link_to 'Edit', edit_about_page_path(about_page) %></td>
        <td><%= link_to 'Destroy', about_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New About page', new_about_page_path %>
</div>

app/views/about_pages/new.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<h1>New About Page</h1>

<%= render 'form' %>

<%= link_to 'Back', about_pages_path %>
</div>

app/views/about_pages/show.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<p id="notice"><%= notice %></p>

<p>
  <strong>Img:</strong>
  <%= @about_page.img %>
</p>

<p>
  <strong>About:</strong>
  <%= @about_page.about %>
</p>

<p>
  <strong>Vision:</strong>
  <%= @about_page.vision %>
</p>

<p>
  <strong>Mission:</strong>
  <%= @about_page.mission %>
</p>

<p>
  <strong>Extra:</strong>
  <%= @about_page.extra %>
</p>

<%= link_to 'Edit', edit_about_page_path(@about_page) %> |
<%= link_to 'Back', about_pages_path %>
</div>